# Generated by Django 4.0.4 on 2022-05-24 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_product_category_product_price_product_sub_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
